name: "Bug: Tales of Rebirth"
description: When the patch is not working as expected
title: "[Bug]: Tales of Rebirth"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Here are some usecases when you should use this template :
        - You tried a new patch and the game crash
        - You found some glitch in some textures
        - Weird things are happening in the game
        
  - type: input
    id: version
    attributes:
      label: Version details
      description: What version of the patch are you using? 
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord name
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 
      ##Description of the problem

      ##How can we replicate the issue?

      ##Screenshot of the issue

      ##Other information
    validations:
      required: true

