name: "Section to translate"
description: "When the community wants new stuff to be translated"
title: "[Translation]: Your short description here"
labels: ["Translation"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: type
    attributes:
      label: What is the type of action?
      multiple: false
      options:
        - Translation
        - Proofreading
        - Review
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What do you want to translate?
      description: Insert any screenshots that might be usefull
      placeholder: "Describe what to translate"
      value:
      ##File Number and Section to use in the app
      
      ##Screenshot inside the game

    validations:
      required: true

